repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.13.2
    set:
      - name: installCRDs
        value: true

  - name: ginny-api
    namespace: ginny
    chart: ./helm/ginny-api
    needs:
      - cert-manager/cert-manager
    values:
      - secretNamespace: ginny
      - ./values-secrets.yaml
      - host: xbauquet.eu
    recreatePods: true
