apiVersion: v1
data:
  .dockerconfigjson: {{ required ".Values.secret.docker is required in common chart." .Values.secret.docker }}
kind: Secret
metadata:
  name: github-packages-secret
  namespace: {{ required ".Values.secretNamespace is required in common chart." .Values.secretNamespace }}
type: kubernetes.io/dockerconfigjson
