name: CI

on: push

env:
  JAVA_VERSION: 19
  JAVA_DISTRIBUTION: temurin

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Build
        run: ./gradlew --no-daemon clean assemble

      - name: Test
        run: ./gradlew --no-daemon test

      - name: Docker
        run: docker build -t image .
