name: Publish

on:
  workflow_dispatch:
    release_type:
      type: choice
      required: true
      default: prod
      description: Release type
      options:
        - prod
    inputs:
      version:
        description: 'New version, if 0.0.0 will bump last git tag.'
        required: true
        default: '0.0.0'
        type: string

permissions:
  contents: write
env:
  JAVA_VERSION: 19
  JAVA_DISTRIBUTION: temurin

jobs:
  Publication:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # fetch all commits and tags
          fetch-depth: "0"

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Build
        run: ./gradlew --no-daemon clean assemble

      - name: Test
        run: ./gradlew --no-daemon test

      - name: Version
        run: |
          if [[ ${{ github.event.inputs.version }} == '0.0.0' ]]
          then
            latest=$(git tag -l --sort=-creatordate | head -n 1)
            majorAndMinor="${latest%.*}."
            patch="${latest##*.}"
            VERSION="$majorAndMinor$((patch+1))"
          else
            VERSION=${{ github.event.inputs.version }}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Docker
        run: |
          echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build --build-arg arg_version=${{ env.VERSION }} -t image .

      - name: Tag
        run: |
          git tag -a ${{ env.VERSION }} -m "${{ env.VERSION }}"
          git push origin --tags

      - name: Push docker image
        run: |
          VERSION=${{ env.VERSION }}
          REPOSITORY_LOWERCASE=$(echo ${{ github.repository }} | sed -e 's/\(.*\)/\L\1/')
          IMAGE_ID=ghcr.io/$REPOSITORY_LOWERCASE
          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Push docker image as latest if prod
        run: |
          REPOSITORY_LOWERCASE=$(echo ${{ github.repository }} | sed -e 's/\(.*\)/\L\1/')
          IMAGE_ID=ghcr.io/$REPOSITORY_LOWERCASE
          docker tag image $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
